### ISSUE TITLE
[bug]: Using `OMZP::` shorthand seems to break `svn` ice

### ISSUE THREAD

**Issue by signed-log** [z-shell/zi#164]
### Environment

OSTYPE=linux-gnu, CPUTYPE=x86_64 / MACHINE_TYPE=x86_64 ZSH_VERSION=5.6

### Expected behavior

Using `zi ice svn` with the `OMZP::` should pull the whole folder

### Current behavior

It fails to load with a `Snippet not loaded` but it seems to have loaded something

### Steps to reproduce

Try to load like this :

```shell
zi ice svn
zi snippet OMZP::history-substring-search # Tested only with HSS
```

### Code snippet

```shell
zi ice svn
#zi snippet OMZ::/plugins/history-substring-search # This form works
zi snippet OMZP::history-substring-search
```

### Aditional information

`zi status --all` without `OMZP::`

```
Status for plugins/history-substring-search
              6455     6205 marc.cornell. history-substring-search.plugin.zsh
?                                        history-substring-search.plugin.zsh.zwc
              6455     5342 marc.cornell. update-from-upstream.zsh
              6455     6130 marc.cornell. history-substring-search.zsh
?                                        history-substring-search.zsh.zwc
              6455     5885 marc.cornell. README.md
?                                        ._zi
              6455     6205 marc.cornell. .
Status against revision:   6455
```

`ls $HOME/.zi/snippets/OMZP::history-substring-search` **with** `OMZP::` (after `zi delete --clean`)

```shell
drwxr-xr-x 3 signed users 4.0K May 28 10:01 history-substring-search.zsh
-rw-r--r-- 1 signed users  638 May 28 10:01 OMZP::history-substring-search
-r--r--r-- 1 signed users 1.4K May 28 10:01 OMZP::history-substring-search.zwc
drwxr-xr-x 2 signed users 4.0K May 28 10:01 ._zi
```

(no sign of `svn` with `OMZP`)

### Self-service

- [ ] I'd be willing to address this documentation request myself.

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/z-shell/community/blob/main/docs/CONTRIBUTING_GUIDELINES.md).

### Are you familiar with Contributor Covenant Code of Conduct?

- [X] I have read the [Contributor Covenant Code of Conduct](https://github.com/z-shell/zi/blob/main/docs/CODE_OF_CONDUCT.md).

### Contact Details

stigpro@outlook.fr

**Comment by ss-o** [comment]
Maybe I am missing out, but it seems you pick a specific file instead of grabbing dir?

```zsh
zi ice svn
zi snippet OMZ::plugins
```

**Comment by signed-log** [comment]
> Maybe I am missing out, but it seems you pick a specific file instead of grabbing dir?
> 
> ```shell
> zi ice svn
> zi snippet OMZ::plugins
> ```

In which one? 
With `OMZP::` it seems to do exactly that. 
With `OMZ::` no, I am selecting the `history-substring-search` folder in its entierety

**Comment by signed-log** [comment]
Can't repro anymore on one of the two impacted machine.

Closing until testing is complete on the other machine

**Comment by signed-log** [comment]
Can reproduce on the second machine :

`echo "OSTYPE=${OSTYPE} CPUTYPE=$(uname -m) / MACHINE_TYPE=$MACHTYPE ZSH_VERSION=${ZSH_VERSION}"`

Output of `zi dtrace` while trying to load the module :

```
Report for[0m [1;4m[38;5;207m_dtrace[0m/[1;4m[38;5;39m_dtrace[0m plugin
[38;5;82m---------------------------------[0m

[ [38;5;82m✔[0m[0m ] [0m[38;5;81mFunctions created:[0m[0m
alias autoload
bindkey zle
zstyle 
[0m[0m

[ [38;5;82m✔[0m[0m ] [0m[38;5;81mVariables added or redefined:[0m[0m
filename [38;5;82m[ "" -> scalar ][0m
fsh__chroma__zi__delete__NO_MATCH__H_opt [38;5;82m[ "" -> association ][0m
fsh__chroma__zi__delete__DELETE_0_opt [38;5;82m[ "" -> association ][0m
__sp [38;5;82m[ "" -> array ][0m
id_as [38;5;82m[ "" -> scalar ][0m
[0m[0m
```

According to this, it didn't even try to load the snippet

**Comment by ss-o** [comment]
I might understand the issue you are having here. I am guessing that: :see_no_evil: 

You might not fully understand how snippets are downloaded/sourced, and probably after reading about [ice/#-src-pick-multisrc](https://z.digitalclouds.dev/docs/guides/syntax/ice/#-src-pick-multisrc) you would use `multisrc''` which should solve your issue.

Let me know :octocat:

**Comment by ss-o** [comment]
@signed-log I think the issue is on ohmyzsh side, I will investigate it, to be sure.
