### ISSUE TITLE
[feat]: Translate ZI

### ISSUE THREAD

**Issue by 0xMRTT** [z-shell/zi#189]
### Feature description

Translate ZI

### Related Code

I think that we can use [GNU Gettext with Crowdin](https://store.crowdin.com/gnu-gettext/) for mangaging translations. We can add an `gh-action` which will pull translations from crowdin and push them into the repo in `i18n/` or `locales/`. In `ZI`, we will use `gettext` each time there is an output.

### Additional Context

https://docs.slackware.com/howtos:misc:internationalization_and_localization_of_shell_scripts
https://store.crowdin.com/gnu-gettext/

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/z-shell/community/blob/main/docs/CONTRIBUTING_GUIDELINES.md).

### Are you familiar with Contributor Covenant Code of Conduct?

- [X] I have read the [Contributor Covenant Code of Conduct](https://github.com/z-shell/zi/blob/main/docs/CODE_OF_CONDUCT.md).

**Comment by ss-o** [comment]
Seems possible, but requires a lot of work. Will add no-stale as low-priority.

**Comment by ss-o** [comment]
For trials, I set this instead of adding to the enterprise. 
- https://crowdin.com/project/z-shell-zi
