### ISSUE TITLE
[docs]: Some pages crash on Safari Browser

### ISSUE THREAD

**Issue by andreseichi** [z-shell/zi#210]
## Expected Behavior

Load all pages of doc https://wiki.zshell.dev with no problem on Safari Browser

## Current Behavior

Some pages crash on Safari Browser

### Crash on initial page

![screenshot](https://user-images.githubusercontent.com/40151349/185674815-464347d1-e489-4131-9557-3962e4dfaf83.png)

![screenshot2](https://user-images.githubusercontent.com/40151349/185675081-7b76a0fe-adda-4a5b-b123-1fe8da705d55.png)

### Crash on page https://wiki.zshell.dev/ecosystem/annexes/bin-gem-node

![screenshot3](https://user-images.githubusercontent.com/40151349/185676812-967c68d3-9b3b-4c1d-a844-c0a4d08205cc.png)

### OS

MacOS High Sierra 10.13.6

### CPU

Intel Core i5 2,3 GHz

### Memory

8 GB 1333 MHz DDR3

### Select the area that is associated with this issue.

ZI (this repository)

### Self-service

- [ ] I'd be willing to address this documentation request myself.

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/z-shell/community/blob/main/docs/CONTRIBUTING_GUIDELINES.md).

### Are you familiar with Contributor Covenant Code of Conduct?

- [X] I have read the [Contributor Covenant Code of Conduct](https://github.com/z-shell/zi/blob/main/docs/CODE_OF_CONDUCT.md).

### Contact Details

andre_seichi@hotmail.com

**Comment by 0xMRTT** [comment]
Hi 👋

Thanks for reporting this issue.

I will reproduce the issue and fixing the issue 🙂.

**Comment by ss-o** [comment]
Hi @andreseichi could you confirm that you are still having the issue? Due to changes made at the same time as the issue was open, it might have been solved already as I was unable to reproduce it.

However, if the issue still exists I will remove the component which has been identified as a potential cause. Thanks.

**Comment by andreseichi** [comment]
Hey @ss-o, the page [Bin Gem Node](https://wiki.zshell.dev/ecosystem/annexes/bin-gem-node) that was crashing before seems fixed now.

However, the [main page](https://wiki.zshell.dev/) still keeps crashing, but now with a different message, shown in the image below.

![image](https://user-images.githubusercontent.com/40151349/201157844-f0bdaae1-b3da-409a-8f2e-288880401200.png)
