### ISSUE TITLE
[bug]: OMZP::aliases not functional

### ISSUE THREAD

**Issue by aidan-gibson** [z-shell/zi#257]
### Environment

Device: apple | darwin21.3.0 | arm64 Shell: /opt/homebrew/bin/zsh | -zsh | zsh-5.9-0-g73d3173 Zi: 572553b2c6326c3609cea593e48745a1da9112fe

### Reproduction steps

```bash
1.In zshrc add `zi snippet OMZP::aliases`
2.Reload terminal
3.Run `acs`

❯ acs
/opt/homebrew/bin/python3: can't open file '/Users/aidangibson/.zi/snippets/OMZP::aliases/cheatsheet.py': [Errno 2] No such file or directory
```
```


### Expected behavior

```bash
After manually adding cheatsheet.py from [aliases repo](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/aliases/) to `~/.zi/snippets/OMZP//aliases`, command works and provides expected output as follows.


acs
[_default]
	airdrop = sh /usr/local/bin/airdropfix.sh
	brew86 = arch -x86_64 /usr/local/bin/brew
	bu = brew update && brew upgrade && ziu
	c = clear
	cat = bat
	conda = load_conda && conda
	diff = diff --color
	ext = cd '\''/Users/aidangibson/Library/Mobile Documents/iCloud~md~obsidian/Documents/Ext Brain'\
	fsh-alias = fast-theme
	intel = arch -x86_64 /bin/zsh
	karabiner = code /Users/aidangibson/.config/karabiner.edn
	ls = ls -G
	pi = python3 -i
	pinentry = pinentry-mac
	python = load_conda && python
	python3.7 = arch -x86_64 /Users/aidangibson/.pyenv/versions/3.7.14/bin/python3.7
	python3.9 = /opt/homebrew/bin/python3.9
	reload = source ~/.zshrc
	rip = rip --graveyard ~/.Trash
	run-help = man
	s = sudo pmset disablesleep 0 && sudo pmset sleepnow
	tree = ls --tree
	which-command = whence
	zshrc = code ~/.zshrc && code ~/.zaliases && code ~/.zshenv

[arch]
	pip3.7 = arch -x86_64 /Users/aidangibson/.pyenv/versions/3.7.14/bin/python3.7 -m pip
	pyenv86 = arch -x86_64 pyenv

[zi]
	zini = zi
	zinit = zi
	ziu = zi self-update && zi delete --yes --quiet --clean && zi update --all --parallel --quiet
	zplugin = zi

```
```


### Current behavior

```bash
Explained above
```

### Code snippet

zi snippet OMZP::aliases

### Additional information

If I'm not mistaken, it appears "snippets" are compiled to .zwc files. This presents a problem for OMZP::aliases, as I don't have the option to load it as a plugin, only a snippet. 

### Self-service

- [ ] I'd be willing to address this documentation request myself.

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/z-shell/community/blob/main/docs/CONTRIBUTING_GUIDELINES.md).

### Are you familiar with the Contributor Covenant Code of Conduct?

- [X] I have read the [Contributor Covenant Code of Conduct](https://github.com/z-shell/zi/blob/main/docs/CODE_OF_CONDUCT.md).

### Contact Details

aidangibson310@gmail.com

**Comment by ss-o** [comment]
One of the solutions would be:

```zsh
zi for nocompile svn \
  multisrc'aliases.plugin.zsh';
  pick'/dev/null' \
    OMZP::aliases
```

> This snippet might be simplified, I just improvised here.

The reason is that you want a single directory in a repository, and subversion is one of the solutions to get it. I am working on more solutions such as GitHub codeload, etc.
