### ISSUE TITLE
[bug]:  git.io/zi-loader url is not working

### ISSUE THREAD

**Issue by rationalthinker1** [z-shell/zi#259]
### Environment

Device: ubuntu | linux-gnu | x86_64 |  /bin/bash | zsh | ubuntu/5.8-3ubuntu1.1

### Reproduction steps

```bash
My zi loader is crashing.
```

### Expected behavior

```bash
to load
```

### Current behavior

```bash
/home/raza/.zshrc:134: command not found: zzinit
/home/raza/.zshrc:136: command not found: zi
/home/raza/.zshrc:136: command not found: zi
/home/raza/.zshrc:137: command not found: zi
/home/raza/.zshrc:137: command not found: zi
/home/raza/.zshrc:138: command not found: zi
/home/raza/.zshrc:138: command not found: zi
/home/raza/.zshrc:139: command not found: zi
/home/raza/.zshrc:139: command not found: zi
/home/raza/.zshrc:140: command not found: zi
/home/raza/.zshrc:140: command not found: zi
/home/raza/.zshrc:141: command not found: zi
/home/raza/.zshrc:141: command not found: zi
/home/raza/.zshrc:142: command not found: zi
/home/raza/.zshrc:142: command not found: zi
/home/raza/.zshrc:143: command not found: zi
/home/raza/.zshrc:144: command not found: zi
/home/raza/.zshrc:144: command not found: zi
/home/raza/.zshrc:145: command not found: zi
/home/raza/.zshrc:145: command not found: zi
/home/raza/.zshrc:146: command not found: zi
/home/raza/.zshrc:146: command not found: zi
/home/raza/.zshrc:147: command not found: zi
/home/raza/.zshrc:147: command not found: zi
/home/raza/.zshrc:148: command not found: zi
```

### Code snippet

```bash
typeset -Ag ZI 
typeset -gx ZI[HOME_DIR]="${LOCAL_CONFIG}/zi" ZI[BIN_DIR]="${ZI[HOME_DIR]}/bin"
command mkdir -p "$ZI[BIN_DIR]"
source <(curl -sL git.io/zi-loader); zzinit         
```

### Additional information

zi analytics is not loading

### Self-service

- [ ] I'd be willing to address this documentation request myself.

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/z-shell/community/blob/main/docs/CONTRIBUTING_GUIDELINES.md).

### Are you familiar with the Contributor Covenant Code of Conduct?

- [X] I have read the [Contributor Covenant Code of Conduct](https://github.com/z-shell/zi/blob/main/docs/CODE_OF_CONDUCT.md).

**Comment by ss-o** [comment]
Hi @rationalthinker1,

It seems the git.io URL has been disabled, I will double-check what is going on. As a quick fix you can use [alternative links](https://wiki.zshell.dev/docs/getting_started/installation#loader): `source <(curl -sL init.zshell.dev); zzinit`

**Comment by rationalthinker1** [comment]
Got it. I loaded the `init.zsh` locally, Thank you.

**Comment by rationalthinker1** [comment]
@ss-o, sorry to bother you, but can you change the installation page to update the url? https://wiki.zshell.dev/docs/getting_started/installation

**Comment by rationalthinker1** [comment]
Perfect. Thank you.
