### ISSUE TITLE
[bug]: Website Down

### ISSUE THREAD

**Issue by rationalthinker1** [z-shell/zi#310]
### Environment

WSL2 Ubuntu 22.04

### Reproduction steps

```bash
In my `.zshrc`, I have this line

source <(curl -sLk init.zshell.dev); zzinit

but the website `init.zshell.dev` is down.
```

### Expected behavior

```bash
It should load up
```

### Current behavior

```bash
command not found zzinit
```

### Code snippet

```bash
source <(curl -sLk init.zshell.dev); zzinit
```

### Additional information

zi won't load

### Self-service

- [ ] I'd be willing to address this documentation request myself.

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/z-shell/community/blob/main/docs/CONTRIBUTING_GUIDELINES.md).

### Are you familiar with the Contributor Covenant Code of Conduct?

- [X] I have read the [Contributor Covenant Code of Conduct](https://github.com/z-shell/zi/blob/main/docs/CODE_OF_CONDUCT.md).

**Comment by yxia-2022** [comment]
Same problem

**Comment by yxia-2022** [comment]
Fixed: replace `source <(curl -sL init.zshell.dev)` with `source <(curl -sL git.io/zi-loader)`

**Comment by g0j0j0** [comment]
Well it appears that the site is now working, and no issue so far on my side when loading zinit with my zshrc config. 
Thanks ! :)
