### ISSUE TITLE
feat: Get plugin directory

### ISSUE THREAD

**Issue by cristianriano** [z-shell/zi#99]
### Feature description

Currently there `zi cd <plugin>` which changes to the directory where the plugin is installed. Getting the info of where the plugin is will be very useful

### If the feature request is approved, would you be willing to submit a PR? (Help can be provided if you need assistance submitting a PR)

Yes

### Related Code

I imagine the feature could look like this
```
zi dir my-plugin
~/.zi/plugins/my-plugin
```

**Comment by ss-o** [comment]
Hey @cristianriano :wave:,

Could you provide more details as your description matches some of the existing features :octocat:

Or simply join https://matrix.to/#/#zi:matrix.org for a discussion :speak_no_evil: :upside_down_face: 

Thanks,
@ss-o ss-o

**Comment by jwdevelab** [comment]
You have in mind something like this?
<a href="https://asciinema.org/a/472313" target="_blank"><img src="https://asciinema.org/a/472313.svg" /></a>

**Comment by ss-o** [comment]
Hey :wave: @cristianriano,

 help us to make ZI Global :globe_with_meridians: :octocat: :upside_down_face: :crossed_fingers:

Spanish translations: https://digitalclouds.crowdin.com/z-shell/es

**Comment by cristianriano** [comment]
Hey @ss-o and @jwdevelab 

Thanks for both your replies.
Basically what I was expecting is a command where you can get in return what's the folder path where a plugin is installed.

Context: I want to set some ENV variables based on the path where the plugin code is. Something like this:
```
MY_PLUGIN_HOME=$(zi dir my_plugin)
```
Perhaps is already supported but I just don't know how to do it 😅 

PS: I will take a look at the Spanish translations if I can help @ss-o

**Comment by ss-o** [comment]
It also seems to exist :upside_down_face:,

You can use ZI internal variables: https://asciinema.org/a/472561

Docs: https://z.digitalclouds.dev/docs/guides/customization#ZI[PLUGINS_DIR]

Let me know if correct or need additional support :octocat: :+1:

**Comment by cristianriano** [comment]
Oh thank you very much! That's exactly what I needed!

```bash
MY_PLUGIN_HOME=$ZI[PLUGINS_DIR]/my-plugin
```

**Comment by ss-o** [comment]
No problem, contact me any time. Also if will need help to get started with translations.

Or just join: https://matrix.to/#/#zi:matrix.org

@ss-o
